language: java

compiler:
- gcc

git:
  depth: 3

sudo: required

dist: trusty

os:
- linux
#- osx

osx_image: xcode9.3

#jdk:
#- openjdk6

cache: ccache

# blocklist
branches:
  except:
  - /circleci.*/
  - /cci.*/

addons:
  apt:
    sources:
    - r-packages-trusty
    packages:
    - scons
    - gfortran
    - libglu1-mesa-dev
    - liblapack-dev
    - liblapacke-dev
    - libfftw3-dev
    - lib32stdc++-4.8-dev
    - libc6-dev-i386
    - gcc-multilib

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons fftw ; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then jdk_switcher use openjdk6; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -qq update; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libmotif-dev ; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libxt-dev ; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libx11-dev ; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libx11-dev:i386 ; fi
- java -version
- gfortran --version

install:
- pwd
- cd ..
- git config --global core.pager ''
- GITHUB_USER=$(dirname ${TRAVIS_REPO_SLUG})
- git clone --depth 3 --branch master https://github.com/${GITHUB_USER}/ovjTools.git

script:
- echo ${TRAVIS_BRANCH} ${TRAVIS_BUILD_DIR} ${TRAVIS_BUILD_ID} ${TRAVIS_BUILD_NUMBER} 
  ${TRAVIS_COMMIT} ${TRAVIS_COMMIT_RANGE} ${TRAVIS_EVENT_TYPE} ${TRAVIS_JOB_ID} 
  ${TRAVIS_JOB_NUMBER} ${TRAVIS_OS_NAME} ${TRAVIS_PULL_REQUEST} ${TRAVIS_PULL_REQUEST_BRANCH}
  ${TRAVIS_PULL_REQUEST_SHA} ${TRAVIS_REPO_SLUG} ${TRAVIS_SUDO} ${TRAVIS_TEST_RESULT} ${TRAVIS_TAG}
- export OVJ_BUILDDIR=$(pwd)
- export OVJ_ROOT=${OVJ_BUILDDIR}/OpenVnmrJ
- export OVJ_TOOLS=${OVJ_BUILDDIR}/ovjTools
- cd ${OVJ_ROOT}
- cp -a ${OVJ_TOOLS}/bin ${OVJ_BUILDDIR}
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${OVJ_ROOT}/scripts/build_release.sh --inova no build package; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ${OVJ_ROOT}/scripts/build_release.sh build package; fi
- ${OVJ_TOOLS}/bin/whatsin $(ls -t ${OVJ_BUILDDIR}/logs/build* | head -1) | tail -60
- ls -l ${OVJ_BUILDDIR}/dvdimage*

after_failure:
- cd ${OVJ_ROOT}
- find ${OVJ_ROOT} -name build.log
- find . -name 'build*' -exec tail -100 {} \;

before_deploy:
- export RELEASE_PKG_FILE=${OVJ_BUILDDIR}/OpenVnmrJ_${TRAVIS_TAG}_${TRAVIS_OS_NAME}.tgz
- cd ${OVJ_BUILDDIR} && tar czf ${RELEASE_PKG_FILE} dvdimage*

deploy:
  provider: releases
  api_key:
    secure: cejxwSd/ur2kP/Y0aJOFuxn9auvac/qY5ElOaryrplupnkfBNdgYTunqH8FL9/ZB11PuRAByi3uJaxvpSMNKYcf8x9Waf4fYJ0Vat7bv2EBKEcFY1Zqt5yetYrccxYPuJ/xXESWRqBH3usTqGaj/AW/RPHrjvht1Oz6/iCc1bMIgnlCbVaJcT4dTegGZ53xz2spGpPwaOs9uE+MKA3r1eJSuVMVx/QQce2QuaGsTI81IYHFeMYtbvgHlcetu/p/AIzFDHqz3oVerZlXCdLBRDDQvsu45I5cPAnlzXS78hFHTbxe8wdnk8XdQ3GbB4KoclrFJRKKYNyFzWffnvnLYh4FYN/ILdvpB+I19O94AA5C91LwjKQVLeW+rJ8mCap9xeoesPGEfwEptyRpGaDbLnt3ZLUo1sZDilpZtms9l2lpn4H4cYdYLKv9j36JEqDAO8/IZByRBXZD3RYmgh4HeXRqCS1KI/6cnfMrb9P/xFNEMzzhwD+oCSfUYm6WvBSv3e2nittSycc4x8GvX2Y3kBTebPQTU53TkdApbMhVW1QT7rjyz3r40Q0HjiLUumXryRcJ0ZfAqat4O8zoZJmm7QQ+/ndizmdE2YMRnW1W7GvZk92THExnlX9UoqJ9c4CmOB95gj07zkeqqGIJIy8vt8fRZvDObfe30Dccz8Y4wqHg=
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
